version: '3'

services: 
  adguardhome: 
    image: adguard/adguardhome
    volumes: 
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    ports: 
      - 53:53
      - 80:80/tcp
      - 3000:3000/tcp
      - 67:67/udp
      - 68:68
      - 443:443/tcp
      - 853:853/tcp
    restart: unless-stopped
    network_mode: "host"
